name: Release Android Library

on:
  push:
    branches: 
      - "release"

jobs:
  build-release:
    name: Build and Release Library
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: Build Android Library
        run: ./gradlew clean assembleRelease

      - name: Read version from gradle.properties
        id: get_version
        run: |
          VERSION_NAME=$(grep "VERSION_NAME" gradle.properties | cut -d'=' -f2)
          echo "VERSION_NAME=$VERSION_NAME"
          echo "version_name=$VERSION_NAME" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.version_name }}
          release_name: Release ${{ env.version_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload .aar to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/build/outputs/aar/your-library-release.aar
          asset_name: your-library-${{ env.version_name }}.aar
          asset_content_type: application/zip
